# fly.toml app configuration file generated for pokerface-meet on 2023-05-08T14:03:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokerface-meet"
primary_region = "den"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
